trigger: none  # No CI build on push

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  rg: 'devops-rg'

stages:

# =====================
# Validate PR Stage
# =====================
- stage: ValidatePR
  displayName: 'Validate Pull Request'
  jobs:
    - job: BuildAndValidate
      displayName: 'Build and Test'
      steps:

        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            codeCoverageToolOption: 'JaCoCo'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - task: Bash@3
          name: NotifyFailure
          displayName: 'Notify if Validation Fails'
          condition: failed()
          inputs:
            targetType: 'inline'
            script: |
              echo "❌ PR validation failed. Fix the issues before merging."

        - task: Bash@3
          name: AutoMerge
          displayName: 'Auto Complete Pull Request if Successful'
          condition: succeeded()
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          inputs:
            targetType: 'inline'
            script: |
              echo "✅ PR validation succeeded. Attempting to auto-complete the PR."

              PR_ID=$(System.PullRequest.PullRequestId)
              ORG_URL=$(System.CollectionUri)
              PROJECT=$(System.TeamProject)
              REPO_ID=$(Build.Repository.ID)

              echo "Merging PR $PR_ID in repo $REPO_ID..."

              curl -X PATCH \
                -H "Content-Type: application/json" \
                -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" \
                -d '{ "autoCompleteSetBy": { "id": "$(Build.RequestedForId)" } }' \
                "${ORG_URL}${PROJECT}/_apis/git/repositories/${REPO_ID}/pullRequests/${PR_ID}?api-version=7.1-preview.1"

