trigger:
- main

pool:
  name: Self_Agent

variables:
  MAVEN_DIR: $(Agent.TempDirectory)\maven
  MAVEN_CACHE: $(Pipeline.Workspace)/.m2
  SOURCE_DIR: $(Build.SourcesDirectory)/Helm/Pet_clinic_project/spring-petclinic
  IMAGE_NAME: yourdockerhubusername/petclinic
  IMAGE_TAG: $(Build.BuildId)

steps:
- checkout: self

# Cache Maven local repo
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | $(SOURCE_DIR)/pom.xml'
    path: $(MAVEN_CACHE)
  displayName: 'Cache Maven local repo'

# Download Maven to temp directory
- powershell: |
    $zipPath = "$(Agent.TempDirectory)\maven.zip"
    Invoke-WebRequest -Uri https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.zip -OutFile $zipPath
  displayName: 'Download Maven'

# Extract Maven to temp directory
- powershell: |
    Expand-Archive -Path "$(Agent.TempDirectory)\maven.zip" -DestinationPath "$(MAVEN_DIR)"
  displayName: 'Extract Maven'

# Run Maven build using correct path
- powershell: |
    $mvnPath = "$(MAVEN_DIR)\apache-maven-3.9.4\bin\mvn.cmd"
    cd "$(SOURCE_DIR)"
    & $mvnPath "clean" "install" "-B" "-Dmaven.repo.local=$(MAVEN_CACHE)"
  displayName: 'Run Maven Build'


# Publish the built JAR as a pipeline artifact
- publish: $(SOURCE_DIR)\target
  artifact: petclinic-jar
  displayName: 'Publish JAR Artifact'

# Install Docker Desktop silently on Windows self-hosted agent
- powershell: |
    $ErrorActionPreference = 'Stop'
    $installerPath = "$env:TEMP\DockerDesktopInstaller.exe"
    
    Invoke-WebRequest -Uri https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe -OutFile $installerPath
    Start-Process -FilePath $installerPath -ArgumentList "install", "--quiet" -Wait
    
    $timeout = 120
    $elapsed = 0
    while (-not (Get-Service -Name com.docker.service -ErrorAction SilentlyContinue | Where-Object { $_.Status -eq 'Running' }) -and $elapsed -lt $timeout) {
      Start-Sleep -Seconds 5
      $elapsed += 5
      Write-Host "Waiting for Docker service to start..."
    }
    
    if ($elapsed -ge $timeout) {
      throw "Docker service failed to start within timeout"
    }
    Write-Host "Docker Desktop installed and running."
  displayName: 'Install Docker Desktop on agent'

# Build Docker image from the correct context
- script: |
    docker build -t $(IMAGE_NAME):$(IMAGE_TAG) $(SOURCE_DIR)
  displayName: 'Build Docker Image'

# Docker login (set DOCKER_USERNAME and DOCKER_PASSWORD as secrets)
- script: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USERNAME) --password-stdin
  displayName: 'Docker Login'

# Push Docker image to registry
- script: |
    docker push $(IMAGE_NAME):$(IMAGE_TAG)
  displayName: 'Push Docker Image'
